# Copyright 2014 Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301 USA
#
# Refer to the README and COPYING files for full details of the license
#
VERSION=$(shell scripts/version_manager.py . version)
NAME=lago
TAR_FILE=${NAME}-${VERSION}.tar
TARBALL_FILE=${TAR_FILE}.gz
SPECFILE=${NAME}.spec
PYTEST=$(shell which py.test)

OUTPUT_DIR=${PWD}
RPM_DIR=${OUTPUT_DIR}/rpmbuild
DIST_DIR=${OUTPUT_DIR}/dist

TAR_DIST_LOCATION=${DIST_DIR}/${TAR_FILE}
TARBALL_DIST_LOCATION=${DIST_DIR}/${TARBALL_FILE}

.PHONY: build rpm srpm ${TARBALL_DIST_LOCATION} check-local dist check ${SPECFILE} docs fullchangelog changelog python-sdist add-extra-files-sdist

changelog:
	echo Creating RPM compatible ChangeLog \
	&& ( \
		scripts/version_manager.py . changelog \
	) > ChangeLog \
	|| ( \
		echo Failed to generate RPM ChangeLog >&2 \
		&& exit 1 \
	)

fullchangelog:
	@if test -d ".git"; then \
		echo Creating FullChangeLog \
		&& ( \
			echo '# Generated by Makefile. Do not edit.'; echo; \
			git log --stat \
		) > FullChangeLog \
		|| ( \
			echo Failed to generate FullChangeLog >&2 \
		); \
	else \
		echo A git clone is required to generate a FullChangeLog >&2; \
	fi

${SPECFILE}: ${SPECFILE}.in changelog
	sed -e "s/@@VERSION@@/${VERSION}/g" \
		${SPECFILE}.in > $@; \
	cat ChangeLog >> $@

build:
	LAGO_VERSION=${VERSION} python setup.py build

check: check-local

check-local:
	@echo "-------------------------------------------------------------"
	@echo "-------------------------------------------------------------"
	@echo "-~      Running style checks                               --"
	@echo "-------------------------------------------------------------"
	scripts/check_style.sh
	@echo "-------------------------------------------------------------"
	@echo "-~      Running static checks                              --"
	@echo "-------------------------------------------------------------"
	flake8
	@echo "-------------------------------------------------------------"
	@echo "-~      Running unit tests                                 --"
	@echo "-------------------------------------------------------------"
	PYTHONPATH=${PWD} python ${PYTEST} -v tests/unit
	@echo "-------------------------------------------------------------"
	@echo "-------------------------------------------------------------"

dist: ${TARBALL_DIST_LOCATION}

python-sdist:
	LAGO_VERSION=${VERSION} python setup.py sdist --dist-dir ${DIST_DIR}

add-extra-files-sdist: changelog fullchangelog
	gunzip ${TARBALL_DIST_LOCATION}
	tar rvf ${TAR_DIST_LOCATION} \
		FullChangeLog \
		ChangeLog
	gzip ${TAR_DIST_LOCATION}

${TARBALL_DIST_LOCATION}: python-sdist add-extra-files-sdist

srpm: dist ${SPECFILE}
	rpmbuild \
		--define "_topdir ${RPM_DIR}" \
		--define "_sourcedir ${DIST_DIR}" \
		-of \
		${SPECFILE}

rpm: dist ${SPECFILE}
	rpmbuild \
		--define "_topdir ${RPM_DIR}" \
		--define "_sourcedir ${DIST_DIR}" \
		-ba \
		${SPECFILE}

clean:
	python setup.py clean
	rm -rf ${DIST_DIR}
	rm -rf ${RPM_DIR}
	rm -rf build "$(REPO_LOCAL_REL_PATH)"
	rm -f ${SPECFILE}
	rm -f AUTHORS

docs:
	$(MAKE) -C docs clean
	$(MAKE) -C docs html
