import os
import distutils.core

distutils.core.setup(
    name='lago',
    version=os.environ['LAGO_VERSION'],
    description=(
        'Deploy and tear down environments of several virtual machines'
    ),
    license='GNU GPLv2+',
    author='Dima Kuznetsov',
    author_email='dkuznets@redhat.com',
    url='redhat.com',
    package_dir={
        'lago': 'lib/lago',
        'ovirtlago': 'contrib/ovirt/lib/ovirtlago'
    },
    packages=['lago', 'ovirtlago'],
    package_data={
        'lago': [
            '*.xml',
            '*.log.conf',
        ],
    },
    provides=['lago', 'ovirtlago'],
    scripts=[
        'lago/lagocli',
        'lago/lagocli-template-repo',
        'contrib/ovirt/ovirtlago/lagocli-ovirt',
    ],
    data_files=[
        (
            'share/lago',
            [
                'bin/sync_templates.py',
                'bin/update_images.py',
            ],
        ),
        (
            'share/lago/setup_scripts',
            [
                'scripts/update_if_needed.sh',
            ],
        ),
        (
            'share/ovirtlago/config/repos',
            [
                'contrib/ovirt/config/repos/ovirt-3.5-external.repo',
                ('contrib/ovirt/config/repos/'
                    'ovirt-master-snapshot-external.repo'),
                'contrib/ovirt/config/repos/ovirt-master-snapshot.repo',
            ],
        ),
        (
            'share/ovirtlago/config/virt',
            [
                'contrib/ovirt/config/virt/centos6.json',
                'contrib/ovirt/config/virt/centos7.json',
                'contrib/ovirt/config/virt/centos7-container.json',
                'contrib/ovirt/config/virt/rhel7.json',
            ],
        ),
        (
            'share/ovirtlago/config/answer-files',
            [
                'contrib/ovirt/config/answer-files/el6_master.conf',
                'contrib/ovirt/config/answer-files/el7_master.conf',
                'contrib/ovirt/config/answer-files/el6_3.5.conf',
                'contrib/ovirt/config/answer-files/el7_3.5.conf',
            ],
        ),
        (
            'share/ovirtlago/setup_scripts',
            [
                'contrib/ovirt/setup_scripts/add_local_repo.sh',
                'contrib/ovirt/setup_scripts/setup_engine.sh',
                'contrib/ovirt/setup_scripts/setup_host.sh',
                'contrib/ovirt/setup_scripts/setup_storage_iscsi.sh',
                'contrib/ovirt/setup_scripts/setup_storage_nfs.sh',
                'contrib/ovirt/setup_scripts/bz_1195882_libvirt_workaround.sh',
                'contrib/ovirt/setup_scripts/setup_container_host.sh',
            ],
        ),
        (
            'share/ovirtlago/test_scenarios',
            [
                'contrib/ovirt/test_scenarios/initialize_engine_el7.py',
                'contrib/ovirt/test_scenarios/bootstrap.py',
                'contrib/ovirt/test_scenarios/create_clean_snapshot.py',
                'contrib/ovirt/test_scenarios/basic_sanity.py',
            ],
        ),
        (
            'share/ovirtlago/examples',
            [
                'contrib/ovirt/examples/rhel7_with_master.sh',
            ],
        ),
        (
            'libexec/ovirtlago',
            [
                'contrib/ovirt/libexec/build_engine_rpms.sh',
                'contrib/ovirt/libexec/build_vdsm_rpms.sh',
                'contrib/ovirt/libexec/build_vdsm-jsonrpc-java_rpms.sh',
                'contrib/ovirt/libexec/build_ioprocess_rpms.sh',
            ],
        ),
        (
            '/etc/lago.d/',
            [
                'etc/lago.d/lago.conf',
                'contrib/ovirt/etc/lago.d/ovirt.conf',
            ],
        ),
        (
            '/etc/mock',
            [
                'contrib/ovirt/mock/epel-6-x86_64_ovirt.cfg',
                'contrib/ovirt/mock/epel-7-x86_64_ovirt.cfg',
            ],
        ),
        (
            '/etc/firewalld/services',
            [
                'contrib/ovirt/firewalld/services/lago.xml',
            ],
        ),
        (
            '/etc/polkit-1/localauthority/50-local.d/',
            [
                'polkit/lago.pkla',
            ],
        ),
        (
            '/etc/sudoers.d',
            [
                'sudo/lago',
            ],
        ),
        (
            '/var/lib/lago/subnets',
            [],
        ),
        (
            '/var/lib/lago/store',
            [],
        ),
        (
            '/var/lib/lago/repos',
            [],
        ),
        (
            '/var/lib/lago/reposync',
            [],
        ),
    ],
)
